sudo: false

language: node_js

cache:
  directories:
    - node_modules

notifications:
  email: false

node_js:
  - 5

before_script:
  - npm prune

script:
- |
  npm run lint
  npm run build
  npm run test:ci
  if [ "${TRAVIS_PULL_REQUEST}" == "true" ]; then
    npm run test:cross-browser
  fi

after_success:
  - npm run semantic-release

branches:
  except:
    - /^v\d+\.\d+\.\d+$/
